name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle/Buildozer/SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle
            ~/.buildozer
            ~/.android
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.spec') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            python3-venv \
            openjdk-17-jdk \
            unzip \
            git \
            zip

      - name: Install Android SDK & Build Tools
        run: |
          SDK="$HOME/android-sdk"
          mkdir -p $SDK/cmdline-tools
          cd $SDK/cmdline-tools
          curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip -o sdk.zip -d latest
          export ANDROID_SDK_ROOT=$SDK
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          yes | sdkmanager --sdk_root=$SDK --licenses
          sdkmanager --sdk_root=$SDK "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Ensure Buildozer entrypoint matches your repo
        run: |
          sed -i 's/main.py =.*/main.py = video_downloader_app.py/' buildozer.spec

      - name: Build APK (debug)
        run: |
          pip install buildozer
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.sha }}
          name: "Build ${{ github.sha }}"
          files: bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
