name: Build Android APK (Kivy + Buildozer)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Cache SDK/Gradle/Buildozer
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.buildozer
            $HOME/android-sdk
          key: ${{ runner.os }}-kivy-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-kivy-

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential git zip unzip wget curl \
            libffi-dev libssl-dev zlib1g-dev libsqlite3-dev \
            autoconf automake libtool pkg-config cmake
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install "buildozer==1.5.0" "cython==0.29.36"

      - name: Install Android SDK & Build-Tools
        run: |
          SDK="$HOME/android-sdk"
          mkdir -p "$SDK/cmdline-tools"
          cd "$SDK/cmdline-tools"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O sdk.zip
          unzip -q sdk.zip -d .
          rm sdk.zip
          
          # corrigir estrutura: move cmdline-tools extraído para "latest"
          mv cmdline-tools latest

          echo "ANDROID_SDK_ROOT=$SDK" >> $GITHUB_ENV
          echo "ANDROID_HOME=$SDK" >> $GITHUB_ENV
          echo "$SDK/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$SDK/platform-tools" >> $GITHUB_PATH
          echo "$SDK/build-tools/33.0.2" >> $GITHUB_PATH

          yes | "$SDK/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$SDK" --licenses
          "$SDK/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$SDK" \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2"



      - name: Debug SDK & AIDL
        run: |
          echo "=== SDK ROOT: $ANDROID_SDK_ROOT ==="
          find $ANDROID_SDK_ROOT/build-tools -name aidl || true
          which aidl || true

      - name: Build APK
        env:
          ANDROIDSDK: ${{ env.ANDROID_SDK_ROOT }}
          ANDROIDNDK: ""   # deixa o Buildozer baixar o NDK correto
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
