name: Build APK

on:
  workflow_dispatch:   # permite rodar manualmente no GitHub
  push:                # ou sempre que fizer push na branch main
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel \
            autoconf automake libtool pkg-config zlib1g-dev libncurses5 libncurses5-dev libffi-dev libssl-dev \
            libsqlite3-dev wget curl unzip
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build with Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4   # ✅ atualizado
        with:
          name: video-downloader-apk
          path: bin/*.apk

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
